from __future__ import annotations

DOCUMENT_TYPE_ALIASES: dict[str, str] = {
    "ds-160": "ds160",
    "ds 160": "ds160",
    "ds160": "ds160",
    "ds-160 confirmation": "ds160",
    "ds 160 confirmation": "ds160",
    "ds160 confirmation": "ds160",
    "ds-160 confirmation page": "ds160",
    "ds 160 confirmation page": "ds160",
    "ds160 confirmation page": "ds160",
    "passport": "passport_bio",
    "passport bio": "passport_bio",
    "passport bio page": "passport_bio",
    "passport biographic page": "passport_bio",
    "passport_bio": "passport_bio",
    "i-20": "i20",
    "i 20": "i20",
    "i20": "i20",
    "form i-20": "i20",
    "form i20": "i20",
    "bank_statement": "funding_proof",
    "bank statement": "funding_proof",
    "financial_statement": "funding_proof",
    "financial statement": "funding_proof",
    "funding_proof": "funding_proof",
    "funding proof": "funding_proof",
    "financial evidence": "funding_proof",
    "sponsor_letter": "funding_proof",
    "sponsor letter": "funding_proof",
    "affidavit_of_support": "funding_proof",
    "affidavit of support": "funding_proof",
    "scholarship_letter": "funding_proof",
    "scholarship letter": "funding_proof",
    "birth_certificate": "relationship_proof_between_applicant_and_sponsors",
    "birth certificate": "relationship_proof_between_applicant_and_sponsors",
    "household_register": "relationship_proof_between_applicant_and_sponsors",
    "household register": "relationship_proof_between_applicant_and_sponsors",
    "hukou": "relationship_proof_between_applicant_and_sponsors",
    "family_register": "relationship_proof_between_applicant_and_sponsors",
    "family register": "relationship_proof_between_applicant_and_sponsors",
    "relationship_proof": "relationship_proof_between_applicant_and_sponsors",
    "relationship proof": "relationship_proof_between_applicant_and_sponsors",
    "relationship proof to sponsor": "relationship_proof_between_applicant_and_sponsors",
    "relationship proof to sponsor if parent-sponsored": "relationship_proof_between_applicant_and_sponsors",
    "relationship_proof_between_applicant_and_sponsors": "relationship_proof_between_applicant_and_sponsors",
    "ds-2019": "ds2019",
    "ds 2019": "ds2019",
    "ds2019": "ds2019",
    "form ds-2019": "ds2019",
    "form ds2019": "ds2019",
    "program invitation": "program_invitation",
    "program_invitation": "program_invitation",
    "exchange program invitation": "program_invitation",
    "sevis fee receipt": "sevis_fee_receipt",
    "sevis i-901 receipt": "sevis_fee_receipt",
    "sevis_fee_receipt": "sevis_fee_receipt",
    "ds-7002": "training_plan_ds7002",
    "ds7002": "training_plan_ds7002",
    "training plan": "training_plan_ds7002",
    "training_plan_ds7002": "training_plan_ds7002",
    "insurance proof": "insurance_proof",
    "insurance_proof": "insurance_proof",
    "itinerary": "itinerary_or_trip_purpose",
    "travel itinerary": "itinerary_or_trip_purpose",
    "trip purpose": "itinerary_or_trip_purpose",
    "itinerary_or_trip_purpose": "itinerary_or_trip_purpose",
    "invitation letter": "invitation_letter",
    "invitation_letter": "invitation_letter",
    "employment proof": "employment_proof",
    "employment_proof": "employment_proof",
    "employment letter": "employment_proof",
    "travel history": "travel_history",
    "travel_history": "travel_history",
    "family ties proof": "family_ties_proof",
    "family_ties_proof": "family_ties_proof",
    "i-797": "i797",
    "i 797": "i797",
    "i797": "i797",
    "form i-797": "i797",
    "form i797": "i797",
    "i-129 petition": "i129_petition",
    "i129 petition": "i129_petition",
    "i129_petition": "i129_petition",
    "employer letter": "employer_letter",
    "employer_letter": "employer_letter",
    "offer letter": "offer_letter",
    "offer_letter": "offer_letter",
    "lca": "lca",
    "labor condition application": "lca",
    "degree certificate": "degree_certificate",
    "degree_certificate": "degree_certificate",
    "resume": "resume",
    "cv": "resume",
    "client letter": "client_letter",
    "client_letter": "client_letter",
}


def normalize_document_type(document_type: str | None) -> str | None:
    if document_type is None:
        return None
    normalized = document_type.strip().lower()
    if not normalized:
        return None
    return DOCUMENT_TYPE_ALIASES.get(normalized, normalized)
